server:
  port: 41100

default:
  language: en #다국어 반환 시 적용되는 기본언어

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/
#      uri: mongodb+srv://mango:banana4apple@dev.2iplu.mongodb.net/mongodemo?retryWrites=true&w=majority
      database: newbie
  application:
    name: board-service


info:
  app:
    name: Board Service
    description: Board Service
    test : local
    version: 1.0.0

logging:
  file:
    path: ./logs





