swagger: "3.0"
info:
  version: v1.0.0
  title: Board-Service API
  contact:
    email: "trdev1@alticast.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /board-service/v1
tags:
  - name: "board"
    description: "게시판 글 조회/등록/수정/삭제"
  - name: "comment"
    description: "댓글 등록/수정/삭제"
  - name: "history"
    description: "게시글 수정/삭제 이력관리"
schemes:
#  - "https"
  - "http"
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
security:
  - ApiKeyAuth: []

paths:
  /board:
    get:
      tags:
        - "board"
      summary: "각 조건에 맞는 검색결과 조회"
      description: "조건에 부합하는 Board 게시글 조회, 별도 조건이 없을경우 전체 조회\n
        [필드명 검색 조건 참고사항] - 각 필드의 value 부분에 아래 조건을 참고하여 검색을 시도 한다.\n
        - eq?{value} -> value값과 일치하는 것 (value 에 null 로 입력시 해당 필드가 null인 상태를 검색)\n
        - ne?{value} -> value값이 아닌 것 (value 에 null 로 입력시 해당 필드가 null이 아닌 상태를 검색)\n
        - lt?{value} -> value보다 작은 것\n
        - le?{value} -> value보다 같거나 작은 것\n
        - gt?{value} -> value보다 큰 것 \n
        - ge?{value} -> value보다 같거나 큰 것 \n
        - in?{value1},{value2},{value3} -> value들이 포함된 것 \n
        - nin?{value1},{value2},{value3} -> value들이 포함되지 않은 것 \n
        - like?{value} -> value와 일부 일치하는 것\n\n
        [q 검색 조건 참고사항]\n
        - value 부분에 {대상필드}%{필터조건}?검색어 순으로 입력하고, 다중 조건의 검색이 필요한 경우 ','구분자를 이용한다.\n
        - 참고1) null인 값을 조회 - {필드명}%eq?null 로 입력하여 검색한다.\n
        - 참고2) null이 아닌 값을 조회 - {필드명}%ne?null 로 입력하여 검색한다.\n
        - ex) 필드명1%in?값1,값2,값3,필드명2%eq?값1,필드명3%eq?null\n\n
        [sorting 참고사항]\n
        - parameter 중 orderBy 부분에 {sorting할필드명}:{sorting방법} 순으로 입력하고, 다중 sorting이 필요한 경우 ','구분자를 이용한다.\n
        - sorting방법은 1 입력시 ASC, -1 입력시 DESC\n
        - 기본정렬은 createdDate DESC로 정렬 됨.\n\n
        [검색 시 주의사항]\n
        - 하나의 필드에 대해 q 검색과 필드명 검색 조건을 중복하여 넣지 않는다.\n\n
        [참고사항]\n
        - 범위(BETWEEN) 검색 필요시 le 와 ge를 활용한다. 아래 가입일시 0 ~ 99999 사이 검색 예제 참고\n
        - ?createdDate=ge?0&createdDate=le?99999\n"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          type: "string"
          name: "postId"
          description: "게시글의 postId 기준 검색(단건조회)"
        - in: "query"
          type: "string"
          name: "category"
          description: "카테고리 기준 검색"
        - in: "query"
          type: "string"
          name: "nickName"
          description: "작성자의 닉네임 기준 검색"
        - in: "query"
          type: "string"
          name: "title"
          description: "제목 기준 검색"
        - in: "query"
          type: "string"
          name: "contents"
          description: "내용 기준 검색"
        - in: "query"
          type: "string"
          name: "q"
          description: "q 검색 조건 참고"
        - in: "query"
          type: number
          name: "page"
          description: "페이지 (default:1)"
        - in: "query"
          type: number
          name: "size"
          description: "페이지 사이즈 (default:10)"
        - in: "query"
          type: string
          name: "orderBy"
          description: "정렬 기준 (default createdDate:-1 desc)"
        - in: "query"
          type: string
          name: "lang"
          description: "다국어 (default all ex: en, ko ...)"
      responses:
        "200":
          description: "return board"
          schema:
            $ref: "./board/board.yaml#/definitions/ResponseBoardListResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
    post:
      tags:
        - "board"
      summary: "게시판 글 작성"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "exposureDate는 게시일자로 미입력시 작성일을 기준으로 노출"
          required: true
          schema:
            $ref: "./board/board.yaml#/definitions/Board"
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "./board/board.yaml#/definitions/ResponseCreateBoardResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{postId}:
    get:
      tags:
        - "board"
      summary: "게시글 조회"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "postId"
          type: "string"
          description: "조회하고자 하는 글의 아이디"
          required: true
      responses:
        "200":
          description: "해당 게시글 반환"
          schema:
            $ref: "./board/board.yaml#/definitions/ResponseBoardResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
    patch:
      tags:
        - "board"
      summary: "게시판 글 수정"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          type: string
          name: "postId"
          description: "수정할 글의 아이디"
          required: true
        - in: "body"
          name: "body"
          description: "body에서 변경 필드만 수정하여 전달"
          required: true
          schema:
            $ref: "./board/board.yaml#/definitions/ModifyBoard"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "./board/board.yaml#/definitions/ResponseModifyBoardResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
    delete:
        tags:
          - "board"
        summary: "작성된 글 삭제"
        consumes:
          - "application/json"
        produces:
          - "application/json"
        parameters:
          - in: "path"
            type: "string"
            name: "postId"
            description: "삭제하고자 하는 글의 아이디"
            required: true
        responses:
          "200":
            description: "ok"
            schema:
              $ref: "./code/code.yaml#/definitions/OK"
          "204":
            description: "No Value Present"
            schema:
              $ref: "./code/code.yaml#/definitions/customException"
          "404":
            description: "Invalid Request"
            schema:
              $ref: "./code/code.yaml#/definitions/404Error"
          "500":
            description: "Internal Server Error"
            schema:
              $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{postId}/history:
    get:
      tags:
        - "history"
      summary: "수정버전 이력조회"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          type: string
          name: "postId"
          description: "조회하고자 하는 수정 버전의 아이디"
          required: true
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "./board/board.yaml#/definitions/HistoryResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{historyId}/history-one:
    get:
      tags:
        - "history"
      summary: "게시글 버전별 조회"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          type: string
          name: "historyId"
          description: "조회하고자 하는 수정 버전의 히스토리 아이디"
          required: true
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "./board/board.yaml#/definitions/BoardHistoryResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{postId}/restoration:
    patch:
      tags:
        - "history"
      summary: "삭제된 글 복원"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          type: "string"
          name: "postId"
          description: "복원하고자 하는 글의 아이디"
          required: true
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "./code/code.yaml#/definitions/OK"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{postId}/comment:
    get:
      tags:
        - "comment"
      summary: "댓글 조회"
      produces:
        - "application/json"
      parameters:
        - in: path
          type: string
          name: "postId"
          description: "댓글 대상 게시글 아이디"
          required: true
        - in: query
          type: number
          name: "page"
          description: "페이지"
        - in: query
          type: number
          name: "size"
          description: "사이즈"
      responses:
        "200":
          description: "return content"
          schema:
            $ref: "./comment/comment.yaml#/definitions/ResponseCommentResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
    post:
      tags:
        - "comment"
      summary: "댓글 등록"
      produces:
        - "application/json"
      parameters:
        - in: path
          type: string
          name: "postId"
          description: "댓글 대상 게시글 아이디"
          required: true
        - in: "body"
          name: "body"
          schema:
            $ref: "./comment/comment.yaml#/definitions/Comment"
          required: true
      responses:
        "200":
          description: "return content"
          schema:
            $ref: "./comment/comment.yaml#/definitions/ResponseCreateCommentResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
  /board/{commentId}/comment:
    patch:
      tags:
        - "comment"
      summary: "댓글 수정"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: "commentId"
          type: string
          description: "댓글의 아이디"
          required: true
        - in: "body"
          name: "body"
          schema:
            $ref: "./comment/comment.yaml#/definitions/ModifyComment"
          required: true
      responses:
        "200":
          description: "return contents"
          schema:
            $ref: "./comment/comment.yaml#/definitions/ResponseModifyCommentResult"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"
    delete:
      tags:
        - "comment"
      summary: "작성된 댓글 삭제"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: "commentId"
          type: string
          description: "삭제하려는 댓글의 아이디"
          required: true
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "./code/code.yaml#/definitions/OK"
        "204":
          description: "No Value Present"
          schema:
            $ref: "./code/code.yaml#/definitions/customException"
        "404":
          description: "Invalid Request"
          schema:
            $ref: "./code/code.yaml#/definitions/404Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "./code/code.yaml#/definitions/InternalServer"

definitions:
  Board:
    $ref: "./board/board.yaml#/definitions/Board"
  ResponseBoard:
    $ref: "./board/board.yaml#/definitions/ResponseBoard"
  ResponseBoardResult:
    $ref: "./board/board.yaml#/definitions/ResponseBoardResult"
  ResponseCreateBoard:
    $ref: "./board/board.yaml#/definitions/ResponseCreateBoard"
  ResponseCreateBoardResult:
    $ref: "./board/board.yaml#/definitions/ResponseCreateBoardResult"

  ModifyBoard:
    $ref: "./board/board.yaml#/definitions/ModifyBoard"
  ResponseModifyBoardResult:
    $ref: "./board/board.yaml#/definitions/ResponseModifyBoardResult"

  Comment:
    $ref: "./comment/comment.yaml#/definitions/Comment"
  ResponseComment:
    $ref: "./comment/comment.yaml#/definitions/ResponseComment"
  ResponseCommentResult:
    $ref: "./comment/comment.yaml#/definitions/ResponseCommentResult"

  ModifyComment:
    $ref: "./comment/comment.yaml#/definitions/ModifyComment"
  ResponseModifyCommentResult:
    $ref: "./comment/comment.yaml#/definitions/ResponseModifyCommentResult"
